ServerRoot "/usr/local/apache2"

Listen 80

LoadModule mpm_event_module modules/mod_mpm_event.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule unixd_module modules/mod_unixd.so
LoadModule dir_module modules/mod_dir.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_http_module modules/mod_proxy_http.so

ServerName localhost

DocumentRoot "/usr/local/apache2/htdocs"

<Directory "/usr/local/apache2/htdocs">
    Options FollowSymLinks
    AllowOverride None
    Require all granted

    DirectoryIndex index.html

    # React Router fallback
    RewriteEngine On

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteRule ^ index.html [L]
</Directory>


# =========================
# Django API
# =========================

ProxyPass        /api/ http://backend:8000/api/
ProxyPassReverse /api/ http://backend:8000/api/


# =========================
# Django Admin
# =========================

ProxyPass        /admin/ http://backend:8000/admin/
ProxyPassReverse /admin/ http://backend:8000/admin/


# =========================
# Django Static Files
# =========================

ProxyPass        /static/ http://backend:8000/static/
ProxyPassReverse /static/ http://backend:8000/static/


# =========================
# Django Media Files
# =========================

ProxyPass        /media/ http://backend:8000/media/
ProxyPassReverse /media/ http://backend:8000/media/